export const Nav: string;
export const Branding: string;
export const Menu: string;
export const visible: string;
export const Items: string;
export const CloseToggle: string;
export const Item: string;
export const Link: string;
export const Toggle: string;
